# Generated by Django 3.2.4 on 2021-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytokens',
            name='access_token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='spotifytokens',
            name='refresh_token',
            field=models.CharField(max_length=150),
        ),
    ]
