# Generated by Django 3.2.4 on 2021-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0005_alter_spotifytokens_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytokens',
            name='top_artists_long',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='spotifytokens',
            name='top_artists_medium',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='spotifytokens',
            name='top_artists_short',
            field=models.JSONField(default=dict),
        ),
    ]
