# Generated by Django 3.2.4 on 2021-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0006_auto_20210613_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytokens',
            name='top_tracks_long',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='spotifytokens',
            name='top_tracks_medium',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='spotifytokens',
            name='top_tracks_short',
            field=models.JSONField(default=dict),
        ),
    ]
