# Generated by Django 3.2.5 on 2022-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0007_auto_20210614_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytokens',
            name='userid',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
